create table if not exists public.crawled_articles (
  article_id text primary key,
  source text not null,
  section text not null default '',
  title text not null,
  subtitle text not null default '',
  phase text not null default 'crawled',
  url text not null,
  article_text text not null,
  input_file_path text not null default '',
  crawled_at timestamptz not null default now(),
  document_json jsonb
);

create index if not exists idx_crawled_articles_source on public.crawled_articles (source);
create index if not exists idx_crawled_articles_crawled_at on public.crawled_articles (crawled_at desc);

create table if not exists public.article_reviews (
  article_id text primary key references public.crawled_articles(article_id) on delete cascade,
  status text not null check (status in ('pending', 'approved', 'deferred', 'rejected')),
  note text not null default '',
  updated_at timestamptz not null default now()
);

create index if not exists idx_article_reviews_status on public.article_reviews (status, updated_at desc);

create table if not exists public.dashboard_user_access (
  id bigint generated by default as identity primary key,
  user_id uuid unique,
  email text unique,
  role text not null check (role in ('supreme_leader', 'authorized', 'pending', 'blocked')),
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid
);

create index if not exists idx_dashboard_user_access_role on public.dashboard_user_access (role, updated_at desc);
create index if not exists idx_dashboard_user_access_email on public.dashboard_user_access (email);

create or replace function public.is_dashboard_supreme_leader()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.dashboard_user_access
    where user_id = auth.uid()
      and role = 'supreme_leader'
  );
$$;

create or replace function public.dashboard_has_supreme_leader()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.dashboard_user_access
    where role = 'supreme_leader'
  );
$$;

grant execute on function public.is_dashboard_supreme_leader() to anon, authenticated;
grant execute on function public.dashboard_has_supreme_leader() to anon, authenticated;

alter table public.dashboard_user_access enable row level security;

drop policy if exists dashboard_user_access_read on public.dashboard_user_access;
create policy dashboard_user_access_read
  on public.dashboard_user_access
  for select
  to authenticated
  using (true);

drop policy if exists dashboard_user_access_bootstrap on public.dashboard_user_access;
create policy dashboard_user_access_bootstrap
  on public.dashboard_user_access
  for insert
  to authenticated
  with check (
    role = 'supreme_leader'
    and user_id = auth.uid()
    and not public.dashboard_has_supreme_leader()
  );

drop policy if exists dashboard_user_access_self_request on public.dashboard_user_access;
create policy dashboard_user_access_self_request
  on public.dashboard_user_access
  for insert
  to authenticated
  with check (
    role = 'pending'
    and user_id = auth.uid()
  );

drop policy if exists dashboard_user_access_supreme_insert on public.dashboard_user_access;
create policy dashboard_user_access_supreme_insert
  on public.dashboard_user_access
  for insert
  to authenticated
  with check (public.is_dashboard_supreme_leader());

drop policy if exists dashboard_user_access_supreme_update on public.dashboard_user_access;
create policy dashboard_user_access_supreme_update
  on public.dashboard_user_access
  for update
  to authenticated
  using (public.is_dashboard_supreme_leader())
  with check (public.is_dashboard_supreme_leader());

drop policy if exists dashboard_user_access_supreme_delete on public.dashboard_user_access;
create policy dashboard_user_access_supreme_delete
  on public.dashboard_user_access
  for delete
  to authenticated
  using (public.is_dashboard_supreme_leader());
