create table if not exists public.crawled_articles (
  article_id text primary key,
  source text not null,
  section text not null default '',
  title text not null,
  subtitle text not null default '',
  phase text not null default 'crawled',
  url text not null,
  article_text text not null,
  input_file_path text not null default '',
  crawled_at timestamptz not null default now(),
  document_json jsonb
);

create index if not exists idx_crawled_articles_source on public.crawled_articles (source);
create index if not exists idx_crawled_articles_crawled_at on public.crawled_articles (crawled_at desc);

create table if not exists public.article_reviews (
  article_id text primary key references public.crawled_articles(article_id) on delete cascade,
  status text not null check (status in ('pending', 'approved', 'deferred', 'rejected')),
  note text not null default '',
  updated_at timestamptz not null default now()
);

create index if not exists idx_article_reviews_status on public.article_reviews (status, updated_at desc);

create table if not exists public.dashboard_user_access (
  id bigint generated by default as identity primary key,
  user_id uuid unique,
  email text unique,
  role text not null check (role in ('supreme_leader', 'authorized', 'pending', 'blocked')),
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  updated_by uuid
);

create index if not exists idx_dashboard_user_access_role on public.dashboard_user_access (role, updated_at desc);
create index if not exists idx_dashboard_user_access_email on public.dashboard_user_access (email);

create or replace function public.is_dashboard_supreme_leader()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.dashboard_user_access
    where user_id = auth.uid()
      and role = 'supreme_leader'
  );
$$;

create or replace function public.dashboard_has_supreme_leader()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.dashboard_user_access
    where role = 'supreme_leader'
  );
$$;

create or replace function public.is_dashboard_authorized()
returns boolean
language sql
security definer
set search_path = public
as $$
  select auth.role() = 'service_role'
    or exists (
      select 1
      from public.dashboard_user_access
      where user_id = auth.uid()
        and role in ('supreme_leader', 'authorized')
    );
$$;

grant execute on function public.is_dashboard_supreme_leader() to anon, authenticated;
grant execute on function public.dashboard_has_supreme_leader() to anon, authenticated;
grant execute on function public.is_dashboard_authorized() to anon, authenticated, service_role;

alter table public.crawled_articles enable row level security;
alter table public.article_reviews enable row level security;
alter table public.dashboard_user_access enable row level security;

drop policy if exists crawled_articles_dashboard_read on public.crawled_articles;
create policy crawled_articles_dashboard_read on public.crawled_articles for select to authenticated using (public.is_dashboard_authorized());

drop policy if exists article_reviews_dashboard_access on public.article_reviews;
create policy article_reviews_dashboard_access on public.article_reviews for all to authenticated using (public.is_dashboard_authorized()) with check (public.is_dashboard_authorized());

drop policy if exists dashboard_user_access_read on public.dashboard_user_access;
create policy dashboard_user_access_read
  on public.dashboard_user_access
  for select
  to authenticated
  using (true);

drop policy if exists dashboard_user_access_bootstrap on public.dashboard_user_access;
create policy dashboard_user_access_bootstrap
  on public.dashboard_user_access
  for insert
  to authenticated
  with check (
    role = 'supreme_leader'
    and user_id = auth.uid()
    and not public.dashboard_has_supreme_leader()
  );

drop policy if exists dashboard_user_access_self_request on public.dashboard_user_access;
create policy dashboard_user_access_self_request
  on public.dashboard_user_access
  for insert
  to authenticated
  with check (
    role = 'pending'
    and user_id = auth.uid()
  );

drop policy if exists dashboard_user_access_supreme_insert on public.dashboard_user_access;
create policy dashboard_user_access_supreme_insert
  on public.dashboard_user_access
  for insert
  to authenticated
  with check (public.is_dashboard_supreme_leader());

drop policy if exists dashboard_user_access_supreme_update on public.dashboard_user_access;
create policy dashboard_user_access_supreme_update
  on public.dashboard_user_access
  for update
  to authenticated
  using (public.is_dashboard_supreme_leader())
  with check (public.is_dashboard_supreme_leader());

drop policy if exists dashboard_user_access_supreme_delete on public.dashboard_user_access;
create policy dashboard_user_access_supreme_delete
  on public.dashboard_user_access
  for delete
  to authenticated
  using (public.is_dashboard_supreme_leader());

create table if not exists public.priority_targets (
  id bigint generated by default as identity primary key,
  label text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.target_sources (
  id bigint generated by default as identity primary key,
  domain text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.pipeline_schedules (
  id bigint generated by default as identity primary key,
  schedule_key text not null unique,
  report_type text not null,
  cadence text not null check (cadence in ('daily', 'weekly')),
  weekdays_json jsonb not null default '[]'::jsonb,
  time_of_day text not null default '09:00',
  timezone_name text not null default 'Asia/Seoul',
  last_enqueued_slot timestamptz,
  last_enqueued_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pipeline_run_requests (
  id bigint generated by default as identity primary key,
  pipeline_key text not null,
  workflow_key text not null,
  trigger_source text not null,
  requested_by text,
  executor text not null default 'local',
  status text not null check (status in ('requested', 'claimed', 'submitted', 'running', 'cancelling', 'cancelled', 'success', 'succeeded', 'failed')),
  payload_json jsonb,
  requested_at timestamptz not null default now(),
  claimed_at timestamptz,
  started_at timestamptz,
  finished_at timestamptz,
  cancel_requested_at timestamptz,
  cancel_requested_by text,
  collection_run_id bigint,
  backend_metadata_json jsonb,
  error_text text,
  created_at timestamptz not null default now()
);

create table if not exists public.collection_runs (
  id bigint generated by default as identity primary key,
  request_id bigint references public.pipeline_run_requests(id) on delete set null,
  cadence text not null,
  run_date date not null,
  status text not null check (status in ('queued', 'running', 'cancelling', 'cancelled', 'success', 'succeeded', 'failed')),
  source_scope text not null,
  executor text,
  started_at timestamptz,
  finished_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.pipeline_run_requests
  drop constraint if exists pipeline_run_requests_collection_run_id_fkey;

alter table public.pipeline_run_requests
  add constraint pipeline_run_requests_collection_run_id_fkey
  foreign key (collection_run_id) references public.collection_runs(id) on delete set null;

create table if not exists public.pipeline_run_steps (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.collection_runs(id) on delete cascade,
  stage_key text not null,
  stage_label text not null,
  stage_detail text not null,
  stage_order integer not null,
  status text not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.artifacts (
  id bigint generated by default as identity primary key,
  run_id bigint references public.collection_runs(id) on delete cascade,
  artifact_type text not null,
  content text,
  file_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.article_evaluations (
  id bigint generated by default as identity primary key,
  run_id bigint references public.collection_runs(id) on delete cascade,
  article_id text not null,
  url text not null,
  title text not null,
  source text not null,
  score numeric not null,
  criteria_json jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_priority_targets_sort_order on public.priority_targets(sort_order, id);
create index if not exists idx_target_sources_sort_order on public.target_sources(sort_order, id);
create index if not exists idx_pipeline_schedules_cadence on public.pipeline_schedules(cadence, schedule_key);
create index if not exists idx_pipeline_run_requests_status on public.pipeline_run_requests(status, requested_at desc);
create index if not exists idx_pipeline_run_requests_collection_run_id on public.pipeline_run_requests(collection_run_id);
create index if not exists idx_collection_runs_status on public.collection_runs(status, created_at desc);
create index if not exists idx_collection_runs_request_id on public.collection_runs(request_id);
create index if not exists idx_pipeline_run_steps_run_order on public.pipeline_run_steps(run_id, stage_order);
create index if not exists idx_artifacts_run_id on public.artifacts(run_id);
create index if not exists idx_article_evaluations_run_score on public.article_evaluations(run_id, score desc);

insert into public.priority_targets (label, sort_order)
values
  ('C1 vocabulary density', 0),
  ('Discussion readiness', 1),
  ('Korean translation quality', 2),
  ('Business relevance', 3),
  ('Chart / media usefulness', 4)
on conflict (label) do nothing;

insert into public.target_sources (domain, sort_order)
values
  ('wsj.com', 0),
  ('ft.com', 1)
on conflict (domain) do nothing;

insert into public.pipeline_schedules (schedule_key, report_type, cadence, weekdays_json, time_of_day, timezone_name)
values
  ('daily_kakao_report', 'daily-kakao-report', 'daily', '[]'::jsonb, '09:00', 'Asia/Seoul'),
  ('weekly_kakao_report', 'weekly-kakao-report', 'weekly', '[]'::jsonb, '09:00', 'Asia/Seoul')
on conflict (schedule_key) do nothing;

alter table public.priority_targets enable row level security;
alter table public.target_sources enable row level security;
alter table public.pipeline_schedules enable row level security;
alter table public.pipeline_run_requests enable row level security;
alter table public.collection_runs enable row level security;
alter table public.pipeline_run_steps enable row level security;
alter table public.artifacts enable row level security;
alter table public.article_evaluations enable row level security;

drop policy if exists priority_targets_dashboard_read on public.priority_targets;
drop policy if exists priority_targets_dashboard_write on public.priority_targets;
drop policy if exists priority_targets_dashboard_access on public.priority_targets;
create policy priority_targets_dashboard_access on public.priority_targets for all to authenticated using (public.is_dashboard_authorized()) with check (public.is_dashboard_authorized());

drop policy if exists target_sources_dashboard_read on public.target_sources;
drop policy if exists target_sources_dashboard_write on public.target_sources;
drop policy if exists target_sources_dashboard_access on public.target_sources;
create policy target_sources_dashboard_access on public.target_sources for all to authenticated using (public.is_dashboard_authorized()) with check (public.is_dashboard_authorized());

drop policy if exists pipeline_schedules_dashboard_read on public.pipeline_schedules;
drop policy if exists pipeline_schedules_dashboard_write on public.pipeline_schedules;
drop policy if exists pipeline_schedules_dashboard_access on public.pipeline_schedules;
create policy pipeline_schedules_dashboard_access on public.pipeline_schedules for all to authenticated using (public.is_dashboard_authorized()) with check (public.is_dashboard_authorized());

drop policy if exists pipeline_run_requests_dashboard_read on public.pipeline_run_requests;
drop policy if exists pipeline_run_requests_dashboard_insert on public.pipeline_run_requests;
drop policy if exists pipeline_run_requests_dashboard_update on public.pipeline_run_requests;
drop policy if exists pipeline_run_requests_dashboard_access on public.pipeline_run_requests;
create policy pipeline_run_requests_dashboard_access on public.pipeline_run_requests for all to authenticated using (public.is_dashboard_authorized()) with check (public.is_dashboard_authorized());

drop policy if exists collection_runs_dashboard_read on public.collection_runs;
create policy collection_runs_dashboard_read on public.collection_runs for select to authenticated using (public.is_dashboard_authorized());
drop policy if exists pipeline_run_steps_dashboard_read on public.pipeline_run_steps;
create policy pipeline_run_steps_dashboard_read on public.pipeline_run_steps for select to authenticated using (public.is_dashboard_authorized());
drop policy if exists artifacts_dashboard_read on public.artifacts;
create policy artifacts_dashboard_read on public.artifacts for select to authenticated using (public.is_dashboard_authorized());
drop policy if exists article_evaluations_dashboard_read on public.article_evaluations;
create policy article_evaluations_dashboard_read on public.article_evaluations for select to authenticated using (public.is_dashboard_authorized());

create or replace function public.article_bot_enqueue_pipeline_request(
  p_trigger_source text,
  p_requested_by text,
  p_cadence text,
  p_workflow_key text,
  p_payload_json jsonb,
  p_backend_metadata_json jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  request_id bigint;
begin
  if not public.is_dashboard_authorized() then
    raise exception 'not-authorized' using errcode = '42501';
  end if;

  if exists (
    select 1
    from public.pipeline_run_requests
    where status in ('requested', 'claimed', 'submitted', 'running', 'cancelling')
    limit 1
  ) or exists (
    select 1
    from public.collection_runs
    where status in ('queued', 'running')
    limit 1
  ) then
    return jsonb_build_object('ok', false, 'reason', 'active-run-exists');
  end if;

  insert into public.pipeline_run_requests (
    pipeline_key,
    workflow_key,
    trigger_source,
    requested_by,
    executor,
    status,
    payload_json,
    requested_at,
    backend_metadata_json
  )
  values (
    'article-bot',
    p_workflow_key,
    p_trigger_source,
    p_requested_by,
    'local',
    'requested',
    p_payload_json,
    now(),
    p_backend_metadata_json
  )
  returning id into request_id;

  return jsonb_build_object('ok', true, 'requestId', request_id);
end;
$$;

create or replace function public.article_bot_claim_next_request()
returns public.pipeline_run_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed public.pipeline_run_requests;
begin
  if not public.is_dashboard_authorized() then
    raise exception 'not-authorized' using errcode = '42501';
  end if;

  with next_request as (
    select id
    from public.pipeline_run_requests
    where status = 'requested'
    order by requested_at asc, id asc
    for update skip locked
    limit 1
  )
  update public.pipeline_run_requests request
  set status = 'claimed',
      claimed_at = now()
  from next_request
  where request.id = next_request.id
  returning request.* into claimed;

  return claimed;
end;
$$;

create or replace function public.article_bot_create_collection_run(p_request_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  request_row public.pipeline_run_requests;
  payload jsonb;
  run_id bigint;
  source_scope text;
begin
  if not public.is_dashboard_authorized() then
    raise exception 'not-authorized' using errcode = '42501';
  end if;

  select *
  into request_row
  from public.pipeline_run_requests
  where id = p_request_id
  limit 1;

  if request_row.id is null then
    raise exception 'request-not-found';
  end if;

  payload := coalesce(request_row.payload_json, '{}'::jsonb);
  select string_agg(value, ',')
  into source_scope
  from jsonb_array_elements_text(coalesce(payload->'sources', '["wsj.com", "ft.com"]'::jsonb));

  insert into public.collection_runs (
    request_id,
    cadence,
    run_date,
    status,
    source_scope,
    executor,
    started_at,
    created_at
  )
  values (
    request_row.id,
    coalesce(payload->>'cadence', 'daily'),
    (now() at time zone 'Asia/Seoul')::date,
    'running',
    coalesce(source_scope, 'wsj.com,ft.com'),
    request_row.executor,
    now(),
    now()
  )
  returning id into run_id;

  update public.pipeline_run_requests
  set collection_run_id = run_id,
      status = 'running',
      started_at = now()
  where id = request_row.id;

  insert into public.pipeline_run_steps (run_id, stage_key, stage_label, stage_detail, stage_order, status, updated_at)
  values
    (run_id, 'load_settings', 'Load criteria', 'Read target sources, evaluation criteria, schedule metadata, and run options.', 0, 'queued', now()),
    (run_id, 'crawl_sources', 'Crawl WSJ / FT', 'Collect fresh stories from Wall Street Journal and Financial Times sections.', 1, 'queued', now()),
    (run_id, 'normalize_articles', 'Normalize articles', 'Canonicalize URLs, fold duplicates, and prepare crawler rows for evaluation.', 2, 'queued', now()),
    (run_id, 'evaluate_articles', 'Evaluate fit', 'Score articles against lesson value, C1 vocabulary, discussion potential, and business relevance.', 3, 'queued', now()),
    (run_id, 'process_articles', 'Process outputs', 'Run translation, summaries, discussion prompts, vocabulary extraction, and media sidecars.', 4, 'queued', now()),
    (run_id, 'deliver_kakao', 'Notify Kakao', 'Build a compact Kakao-ready brief with links back to the dashboard.', 5, 'queued', now());

  return run_id;
end;
$$;

create or replace function public.article_bot_cancel_active_pipeline_request(p_requested_by text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  request_row public.pipeline_run_requests;
  next_status text;
begin
  if not public.is_dashboard_authorized() then
    raise exception 'not-authorized' using errcode = '42501';
  end if;

  select *
  into request_row
  from public.pipeline_run_requests
  where status in ('requested', 'claimed', 'submitted', 'running', 'cancelling')
  order by requested_at desc, id desc
  limit 1;

  if request_row.id is null then
    return jsonb_build_object('ok', false, 'reason', 'no-active-request');
  end if;

  next_status := case when request_row.status in ('requested', 'claimed') then 'cancelled' else 'cancelling' end;

  update public.pipeline_run_requests
  set status = next_status,
      finished_at = case when next_status = 'cancelled' then coalesce(finished_at, now()) else finished_at end,
      cancel_requested_at = coalesce(cancel_requested_at, now()),
      cancel_requested_by = coalesce(cancel_requested_by, p_requested_by),
      error_text = case when next_status = 'cancelled' then coalesce(error_text, 'Cancelled from ' || p_requested_by) else error_text end
  where id = request_row.id;

  if next_status = 'cancelled' and request_row.collection_run_id is not null then
    update public.collection_runs
    set status = 'cancelled',
        finished_at = coalesce(finished_at, now()),
        notes = coalesce(notes, 'Cancelled from ' || p_requested_by)
    where id = request_row.collection_run_id;

    update public.pipeline_run_steps
    set status = 'cancelled',
        updated_at = now()
    where run_id = request_row.collection_run_id
      and status in ('queued', 'running');
  end if;

  return jsonb_build_object('ok', true, 'requestId', request_row.id, 'status', next_status);
end;
$$;

revoke all on function public.article_bot_enqueue_pipeline_request(text, text, text, text, jsonb, jsonb) from public;
grant execute on function public.article_bot_enqueue_pipeline_request(text, text, text, text, jsonb, jsonb) to authenticated, service_role;
revoke all on function public.article_bot_claim_next_request() from public;
revoke execute on function public.article_bot_claim_next_request() from authenticated;
grant execute on function public.article_bot_claim_next_request() to service_role;
revoke all on function public.article_bot_create_collection_run(bigint) from public;
revoke execute on function public.article_bot_create_collection_run(bigint) from authenticated;
grant execute on function public.article_bot_create_collection_run(bigint) to service_role;
revoke all on function public.article_bot_cancel_active_pipeline_request(text) from public;
grant execute on function public.article_bot_cancel_active_pipeline_request(text) to authenticated, service_role;
